h2:
  server:
    enabled: true
    tcp:
      enabled: true
      allow-others: true
      port: 9092
    web:
      enabled: true
      allow-others: true
      port: 8082
#    console:
#      enable: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
